language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

install:
    cpanm --quiet --installdeps --notest . && cpanm --quiet --notest Devel::Cover::Report::Coveralls

script:
    - ./Build testcover

after_success:
    - cover -report coveralls
